sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - develop
notifications:
  email: false
node_js:
  - 4.0
matrix:
  fast_finish: true
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
script:
  - npm run test:coverage
  - npm run test:coverage:check
after_success:
  - npm i -g coveralls@latest
  - cat ./coverage/lcov.info | coveralls
  - npm run build
  - npm run release
